/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author igeni
 */
public class IngresoEmpleados extends javax.swing.JPanel {

    Clases.Conexion conexion = new Clases.Conexion();
    Clases.InsertarEmpleado Insercion = new Clases.InsertarEmpleado();
    Clases.Contrasena encriptado = new Clases.Contrasena();
    Clases.Telefono telefono = new Clases.Telefono();
    DefaultTableModel empleados = new DefaultTableModel();
    DefaultTableModel clientes = new DefaultTableModel();
    int seleccionado = 0;
    
    public IngresoEmpleados() {
        initComponents();
        PAdministrador.setVisible(false);
        PEmpleado.setVisible(true);
        PTelefono.setVisible(false);
        RBEmpleado.setSelected(true);
        RBAdministrador.setSelected(false);
        conexion.ConectarBaseDatos();
        TFNombres.setEnabled(true);
        TFDireccion.setEnabled(true);
        TFApellidos.setEnabled(true);
        BTNAgregar.setEnabled(true);
        TFUsuario.setEnabled(false);
        PFContrasena.setEnabled(false);
        BTNAgregar1.setEnabled(false);
        BTNTelefono.setEnabled(false);
        TFTelefono.setEnabled(false);
        empleados.addColumn("Nombres");
        empleados.addColumn("Apellidos");
        empleados.addColumn("Dirección");
        empleados.addColumn("Estado");
        empleados.addColumn("Usuario");
        TEmpleados.setModel(empleados);
        clientes.addColumn("Telefonos");
        TTelefonos.setModel(clientes);
        Insercion.Buscar(empleados);
        //Insercion.Buscar(jComboBox1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        LBLPanel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEmpleados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TTelefonos = new javax.swing.JTable();
        PEmpleado = new javax.swing.JPanel();
        LBLNombre = new javax.swing.JLabel();
        TFNombres = new javax.swing.JTextField();
        LBLApellidos = new javax.swing.JLabel();
        TFApellidos = new javax.swing.JTextField();
        LBLDireccion = new javax.swing.JLabel();
        TFDireccion = new javax.swing.JTextField();
        BTNAgregar = new javax.swing.JButton();
        PAdministrador = new javax.swing.JPanel();
        BTNAgregar1 = new javax.swing.JButton();
        LBLUsuario = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        LBLContrasena = new javax.swing.JLabel();
        PFContrasena = new javax.swing.JPasswordField();
        PTelefono = new javax.swing.JPanel();
        LBLTelefono = new javax.swing.JLabel();
        TFTelefono = new javax.swing.JTextField();
        BTNTelefono = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        RBAdministrador = new javax.swing.JRadioButton();
        RBEmpleado = new javax.swing.JRadioButton();

        panel1.setBackground(new java.awt.Color(36, 41, 46));

        LBLPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLPanel.setForeground(new java.awt.Color(255, 255, 255));
        LBLPanel.setText("Ingreso de empleados");

        TEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dirección", "Usuario"
            }
        ));
        TEmpleados.setFocusable(false);
        TEmpleados.getTableHeader().setReorderingAllowed(false);
        TEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TEmpleados);

        TTelefonos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teléfono"
            }
        ));
        TTelefonos.setFocusable(false);
        TTelefonos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TTelefonos);

        PEmpleado.setBackground(new java.awt.Color(36, 41, 46));

        LBLNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLNombre.setForeground(new java.awt.Color(255, 255, 255));
        LBLNombre.setText("Nombres:");

        TFNombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFNombres.setName(""); // NOI18N
        TFNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNombresActionPerformed(evt);
            }
        });
        TFNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFNombresKeyTyped(evt);
            }
        });

        LBLApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLApellidos.setForeground(new java.awt.Color(255, 255, 255));
        LBLApellidos.setText("Apellidos:");

        TFApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFApellidosKeyTyped(evt);
            }
        });

        LBLDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLDireccion.setForeground(new java.awt.Color(255, 255, 255));
        LBLDireccion.setText("Dirección:");

        TFDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDireccionActionPerformed(evt);
            }
        });
        TFDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFDireccionKeyTyped(evt);
            }
        });

        BTNAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado.png"))); // NOI18N
        BTNAgregar.setBorder(null);
        BTNAgregar.setBorderPainted(false);
        BTNAgregar.setContentAreaFilled(false);
        BTNAgregar.setFocusPainted(false);
        BTNAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado2.png"))); // NOI18N
        BTNAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado1.png"))); // NOI18N
        BTNAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PEmpleadoLayout = new javax.swing.GroupLayout(PEmpleado);
        PEmpleado.setLayout(PEmpleadoLayout);
        PEmpleadoLayout.setHorizontalGroup(
            PEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadoLayout.createSequentialGroup()
                .addGroup(PEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEmpleadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PEmpleadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFNombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PEmpleadoLayout.setVerticalGroup(
            PEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PAdministrador.setBackground(new java.awt.Color(36, 41, 46));

        BTNAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregarp.png"))); // NOI18N
        BTNAgregar1.setBorder(null);
        BTNAgregar1.setBorderPainted(false);
        BTNAgregar1.setContentAreaFilled(false);
        BTNAgregar1.setFocusPainted(false);
        BTNAgregar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAgregar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_click.png"))); // NOI18N
        BTNAgregar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_mouse.png"))); // NOI18N
        BTNAgregar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAgregar1ActionPerformed(evt);
            }
        });

        LBLUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario.setText("Usuario:");

        TFUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFUsuarioActionPerformed(evt);
            }
        });
        TFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFUsuarioKeyTyped(evt);
            }
        });

        LBLContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLContrasena.setForeground(new java.awt.Color(255, 255, 255));
        LBLContrasena.setText("Contraseña:");

        PFContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout PAdministradorLayout = new javax.swing.GroupLayout(PAdministrador);
        PAdministrador.setLayout(PAdministradorLayout);
        PAdministradorLayout.setHorizontalGroup(
            PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAdministradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PAdministradorLayout.setVerticalGroup(
            PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PTelefono.setBackground(new java.awt.Color(36, 41, 46));

        LBLTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLTelefono.setForeground(new java.awt.Color(255, 255, 255));
        LBLTelefono.setText("Teléfono/Celular del empleado:");

        TFTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefonoKeyTyped(evt);
            }
        });

        BTNTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono.png"))); // NOI18N
        BTNTelefono.setBorder(null);
        BTNTelefono.setBorderPainted(false);
        BTNTelefono.setContentAreaFilled(false);
        BTNTelefono.setFocusPainted(false);
        BTNTelefono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNTelefono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono2.png"))); // NOI18N
        BTNTelefono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono1.png"))); // NOI18N
        BTNTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PTelefonoLayout = new javax.swing.GroupLayout(PTelefono);
        PTelefono.setLayout(PTelefonoLayout);
        PTelefonoLayout.setHorizontalGroup(
            PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTelefonoLayout.createSequentialGroup()
                        .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTelefonoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTelefonoLayout.createSequentialGroup()
                                .addComponent(BTNTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTelefonoLayout.createSequentialGroup()
                                .addComponent(LBLTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        PTelefonoLayout.setVerticalGroup(
            PTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(36, 41, 46));

        RBAdministrador.setBackground(new java.awt.Color(36, 41, 46));
        RBAdministrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        RBAdministrador.setText("Administrador");
        RBAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBAdministradorActionPerformed(evt);
            }
        });

        RBEmpleado.setBackground(new java.awt.Color(36, 41, 46));
        RBEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        RBEmpleado.setText("Empleado");
        RBEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(RBAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(RBEmpleado)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBAdministrador)
                    .addComponent(RBEmpleado)))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(PAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)))
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(PTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(LBLPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1040, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(LBLPanel)
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDireccionActionPerformed

    }//GEN-LAST:event_TFDireccionActionPerformed

    private void TFDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDireccionKeyTyped
        int maximo = 45;
        if (TFDireccion.getText().length()>= maximo)
            evt.consume();
    }//GEN-LAST:event_TFDireccionKeyTyped

    private void TFApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFApellidosKeyTyped
        int maximo = 30;
        if (TFApellidos.getText().length()>= maximo)
            evt.consume();
    }//GEN-LAST:event_TFApellidosKeyTyped

    private void BTNAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAgregarActionPerformed
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        seleccionado = -1;
        if (TFDireccion.getText().length() > 0 && TFApellidos.getText().length() > 0 && TFNombres.getText().length() > 0)
        {
            try {
                Insercion.Insertar(TFNombres.getText(), TFApellidos.getText(), TFDireccion.getText());
                TFDireccion.setText("");
                TFApellidos.setText("");
                TFNombres.setText(""); 
                TFUsuario.setEnabled(false);
                PFContrasena.setEnabled(false);
                PTelefono.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
            while(empleados.getRowCount()>0)
                empleados.removeRow(0);
            while(clientes.getRowCount()>0)
                clientes.removeRow(0);
        }
            
        Insercion.Buscar(empleados);
        PTelefono.setVisible(false);
    }//GEN-LAST:event_BTNAgregarActionPerformed

    private void TFNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNombresActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_TFNombresActionPerformed

    
        private void ValidarNombreYApellido(JTextField textfield, boolean direccion)
    {
        textfield.addKeyListener(new KeyAdapter()
{
   public void keyTyped(KeyEvent e)
   {
      char caracter = e.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         e.consume();  // ignorar el evento de teclado
      }
   }
});
        /*textfield.addKeyListener(new KeyAdapter());
        {
            public void keyTyped(KeyEvent e)
            {
                char caracter = e.getKeyChar();
                
                // Verificar si la tecla pulsada no es un digito ni una letra minuscula o mayuscula
                /*if((((caracter < '0') || (caracter > '9')) && ((caracter < 'a') || (caracter > 'z')) && ((caracter < 'A') || (caracter > 'Z'))) && (caracter == 'Ñ') && (caracter != '\b' ))
                /*{
                    if (direccion == true)
                    {
                        if (caracter != '-')
                            e.consume();  // ignorar el evento de teclado
                    }
                    else
                        e.consume();  // ignorar el evento de teclado
                }/*
            }
        });*/
    }
    
    private void TFNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNombresKeyTyped

        int maximo = 30;
        if (TFTelefono.getText().length()>= maximo)
            evt.consume();
    }//GEN-LAST:event_TFNombresKeyTyped

    private void TFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoKeyTyped
        ValidarNombreYApellido(TFNombres, false);
        int maximo = 45;
        if (TFTelefono.getText().length()>= maximo)
            evt.consume();
    }//GEN-LAST:event_TFTelefonoKeyTyped

    private void BTNTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTelefonoActionPerformed
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        if (TFTelefono.getText().length() > 0)
        {
            if (TEmpleados.getSelectedRow() != -1)
            {
                try {
                    telefono.Insertar(TFTelefono.getText(), TEmpleados.getSelectedRow() + 1);
                    TFUsuario.setText("");
                    telefono.Buscar(clientes, TEmpleados.getSelectedRow() + 1);
                } catch (SQLException ex) {
                    Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado)");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor rellene el campo que le solicita ingresar un telefono)");
        }
    }//GEN-LAST:event_BTNTelefonoActionPerformed

    private void TFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUsuarioActionPerformed

    private void TFUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsuarioKeyTyped
        int maximo = 45;
        if (TFTelefono.getText().length()>= maximo)
            evt.consume();
    }//GEN-LAST:event_TFUsuarioKeyTyped

    private void TEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleadosMouseClicked
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        int indice = TEmpleados.getSelectedRow() + 1;
        seleccionado = indice;
        TableModel modelo = TEmpleados.getModel();
        telefono.Buscar(clientes, indice);
        BTNTelefono.setEnabled(true);
        TFTelefono.setEnabled(true);
        PTelefono.setVisible(true);
        LBLTelefono.setText("Teléfono/Celular de " + String.valueOf(empleados.getValueAt(TEmpleados.getSelectedRow(),0)));
        LBLUsuario.setText("Usuario de " + String.valueOf(empleados.getValueAt(TEmpleados.getSelectedRow(),0)) + ":");
    }//GEN-LAST:event_TEmpleadosMouseClicked

    private void BTNAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAgregar1ActionPerformed
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        if (TFUsuario.getText().length() > 0 && PFContrasena.getPassword().length > 0)
        {
            try {
                if (seleccionado > 0){
                    if (!Insercion.BuscarUsuario(TFUsuario.getText()))
                    {
                        Insercion.InsertarUsuario(TFUsuario.getText(), encriptado.Encriptar(String.valueOf(PFContrasena.getPassword())), seleccionado);
                        TFUsuario.setText("");
                        PFContrasena.setText("");
                    }
                    else
                    {
                        TFUsuario.setText("");
                        PFContrasena.setText("");
                        JOptionPane.showMessageDialog(null, "El usuario ingresado ya existe");
                    }
                }
                else
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado");
            } catch (SQLException ex) {
                Logger.getLogger(IngresoEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            if (TFUsuario.getText().length() == 0)
                JOptionPane.showMessageDialog(null, "Por favor rellene el campo de usuario");
            else if (PFContrasena.getPassword().length == 0)
                JOptionPane.showMessageDialog(null, "Por favor rellene el campo de contraseña");
        }
        Insercion.Buscar(empleados);
        seleccionado = -1;
        PTelefono.setVisible(false);
        LBLUsuario.setText("Usuario:");
    }//GEN-LAST:event_BTNAgregar1ActionPerformed

    private void RBEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEmpleadoActionPerformed
        if (RBEmpleado.isSelected())
            RBAdministrador.setSelected(false);
        PAdministrador.setVisible(false);
        PEmpleado.setVisible(true);
        TFNombres.setEnabled(true);
        TFDireccion.setEnabled(true);
        TFApellidos.setEnabled(true);
        BTNAgregar.setEnabled(true);
        TFUsuario.setEnabled(false);
        PFContrasena.setEnabled(false);
        BTNAgregar1.setEnabled(false);
    }//GEN-LAST:event_RBEmpleadoActionPerformed

    private void RBAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBAdministradorActionPerformed
        if (RBAdministrador.isSelected())
            RBEmpleado.setSelected(false);
        PAdministrador.setVisible(true);
        PEmpleado.setVisible(false);
        TFNombres.setEnabled(false);
        TFDireccion.setEnabled(false);
        TFApellidos.setEnabled(false);
        BTNAgregar.setEnabled(false);
        TFUsuario.setEnabled(true);
        PFContrasena.setEnabled(true);
        BTNAgregar1.setEnabled(true);
    }//GEN-LAST:event_RBAdministradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAgregar;
    private javax.swing.JButton BTNAgregar1;
    private javax.swing.JButton BTNTelefono;
    private javax.swing.JLabel LBLApellidos;
    private javax.swing.JLabel LBLContrasena;
    private javax.swing.JLabel LBLDireccion;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JLabel LBLPanel;
    private javax.swing.JLabel LBLTelefono;
    private javax.swing.JLabel LBLUsuario;
    private javax.swing.JPanel PAdministrador;
    private javax.swing.JPanel PEmpleado;
    private javax.swing.JPasswordField PFContrasena;
    private javax.swing.JPanel PTelefono;
    private javax.swing.JRadioButton RBAdministrador;
    private javax.swing.JRadioButton RBEmpleado;
    private javax.swing.JTable TEmpleados;
    private javax.swing.JTextField TFApellidos;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFNombres;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JTable TTelefonos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
