/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.BorderLayout;

/**
 *
 * @author Usuario
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        pnlProducto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentas = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        pnlContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNitClient = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombreClient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtDireccionClient = new javax.swing.JTextField();
        pnlProducto = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDespachar = new javax.swing.JButton();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setBackground(new java.awt.Color(36, 41, 46));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentas.setText("Venta");
        add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, 130, 46));

        btnConsultas.setText("Consultas");
        add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 6, 130, 46));

        pnlContenedor.setBackground(new java.awt.Color(36, 41, 46));
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Clinte:");
        pnlContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        pnlContenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        pnlContenedor.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 260, 10));

        txtNitClient.setBackground(new java.awt.Color(36, 41, 46));
        txtNitClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNitClient.setForeground(new java.awt.Color(255, 255, 255));
        txtNitClient.setAlignmentX(1.0F);
        txtNitClient.setAlignmentY(1.0F);
        txtNitClient.setBorder(null);
        pnlContenedor.add(txtNitClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, 260, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Direccion:");
        pnlContenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));
        pnlContenedor.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 310, 10));

        txtNombreClient.setBackground(new java.awt.Color(36, 41, 46));
        txtNombreClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombreClient.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreClient.setAlignmentX(1.0F);
        txtNombreClient.setAlignmentY(1.0F);
        txtNombreClient.setBorder(null);
        pnlContenedor.add(txtNombreClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nit:");
        pnlContenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, -1, -1));
        pnlContenedor.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 310, 10));

        txtDireccionClient.setBackground(new java.awt.Color(36, 41, 46));
        txtDireccionClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDireccionClient.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccionClient.setAlignmentX(1.0F);
        txtDireccionClient.setAlignmentY(1.0F);
        txtDireccionClient.setBorder(null);
        pnlContenedor.add(txtDireccionClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 310, 40));

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pnlContenedor.add(pnlProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 960, 600));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Listado de Productos:");
        pnlContenedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        btnProductos.setText("Ingresar Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        pnlContenedor.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 150, 46));

        jButton1.setText("Descuento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlContenedor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, 46));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descuento:");
        pnlContenedor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total a pagar:");
        pnlContenedor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 400, -1, -1));

        btnDespachar.setText("Despachar");
        pnlContenedor.add(btnDespachar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, 46));

        pnlTabla.setBackground(new java.awt.Color(36, 41, 46));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pnlContenedor.add(pnlTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 940, 500));

        add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1420, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        pnlTabla.setVisible(false);
        pnlProducto.setVisible(true);
        Productos_panels.ListarProducto Listar = new Productos_panels.ListarProducto();
        Listar.setSize(9600,600);
        Listar.setLocation(0,0);
        pnlProducto.removeAll();
        pnlProducto.add(Listar,BorderLayout.CENTER);
        pnlProducto.revalidate();
        pnlProducto.repaint();
      
    }//GEN-LAST:event_btnProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnDespachar;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtDireccionClient;
    private javax.swing.JTextField txtNitClient;
    private javax.swing.JTextField txtNombreClient;
    // End of variables declaration//GEN-END:variables
}
