/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Conexion;
import java.awt.BorderLayout;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    private String ColumnaVentas[] = {"Producto","Cantidad","Descripcion","Q. Unitario","Total"};
    private DefaultTableModel ModeloVentas,ModeloProductos;
    private Connection ConexionBaseDatos;
    public Ventas() {
        initComponents();
       Grupo1.add(RbYarda);
       Grupo1.add(RbRollos);
       Grupo1.add(RbMillar);
       Grupo1.add(RbCientos);
       
       ModeloProductos = new DefaultTableModel();
       ModeloVentas = new DefaultTableModel();
       ModeloVentas.setColumnIdentifiers(ColumnaVentas);        
       TableVentas.setModel(ModeloVentas);
        
       //Conexion a la base de datos
       Clases.Conexion con = new Conexion();
       ConexionBaseDatos = con.ConectarBaseDatos();
    //   ConexionBaseDatos = Clases.Conexion.getConnection();
       
       TablaVentas();
    }
    private void TablaVentas(){
       ModeloProductos.addColumn("Nombre Producto"); ModeloProductos.addColumn("Existencia");
       TablaProductos.setModel(Clases.Ventas.MostrarProducto(ModeloProductos, ConexionBaseDatos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlVentas = new javax.swing.JPanel();
        pnlContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNitClient = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombreClient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtDireccionClient = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDespachar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableVentas = new javax.swing.JTable();
        RbYarda = new javax.swing.JRadioButton();
        RbCientos = new javax.swing.JRadioButton();
        RbMillar = new javax.swing.JRadioButton();
        RbRollos = new javax.swing.JRadioButton();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pnlConsultas = new javax.swing.JPanel();

        setBackground(new java.awt.Color(36, 41, 46));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        pnlVentas.setBackground(new java.awt.Color(36, 41, 46));

        pnlContenedor.setBackground(new java.awt.Color(36, 41, 46));
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Clinte:");
        pnlContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        pnlContenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        pnlContenedor.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 260, 10));

        txtNitClient.setBackground(new java.awt.Color(36, 41, 46));
        txtNitClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNitClient.setForeground(new java.awt.Color(255, 255, 255));
        txtNitClient.setAlignmentX(1.0F);
        txtNitClient.setAlignmentY(1.0F);
        txtNitClient.setBorder(null);
        pnlContenedor.add(txtNitClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, 260, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Direccion:");
        pnlContenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));
        pnlContenedor.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 310, 10));

        txtNombreClient.setBackground(new java.awt.Color(36, 41, 46));
        txtNombreClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNombreClient.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreClient.setAlignmentX(1.0F);
        txtNombreClient.setAlignmentY(1.0F);
        txtNombreClient.setBorder(null);
        pnlContenedor.add(txtNombreClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nit:");
        pnlContenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, -1, -1));
        pnlContenedor.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 190, 10));
        pnlContenedor.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 310, 10));

        txtDireccionClient.setBackground(new java.awt.Color(36, 41, 46));
        txtDireccionClient.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDireccionClient.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccionClient.setAlignmentX(1.0F);
        txtDireccionClient.setAlignmentY(1.0F);
        txtDireccionClient.setBorder(null);
        pnlContenedor.add(txtDireccionClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 310, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Listado de Productos:");
        pnlContenedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jButton1.setText("Descuento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlContenedor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, 46));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descuento:");
        pnlContenedor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 670, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total a pagar:");
        pnlContenedor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 670, -1, -1));

        btnDespachar.setText("Despachar");
        pnlContenedor.add(btnDespachar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, 46));

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaProductos);

        pnlContenedor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 340, 470));

        TableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TableVentas);

        pnlContenedor.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 630, 440));

        RbYarda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RbYarda.setForeground(new java.awt.Color(255, 255, 255));
        RbYarda.setText("Yarda");
        pnlContenedor.add(RbYarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        RbCientos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RbCientos.setForeground(new java.awt.Color(255, 255, 255));
        RbCientos.setText("Cientos");
        pnlContenedor.add(RbCientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        RbMillar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RbMillar.setForeground(new java.awt.Color(255, 255, 255));
        RbMillar.setText("Millar");
        pnlContenedor.add(RbMillar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        RbRollos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RbRollos.setForeground(new java.awt.Color(255, 255, 255));
        RbRollos.setText("Rollos");
        pnlContenedor.add(RbRollos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        txtCantidad.setBackground(new java.awt.Color(36, 41, 46));
        txtCantidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setAlignmentX(1.0F);
        txtCantidad.setAlignmentY(1.0F);
        txtCantidad.setBorder(null);
        pnlContenedor.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 180, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");
        pnlContenedor.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jButton2.setText("Aceptar");
        pnlContenedor.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, 46));

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1418, Short.MAX_VALUE)
            .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1418, Short.MAX_VALUE))
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
            .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", pnlVentas);

        pnlConsultas.setBackground(new java.awt.Color(36, 41, 46));

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1418, Short.MAX_VALUE)
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consultas", pnlConsultas);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JRadioButton RbCientos;
    private javax.swing.JRadioButton RbMillar;
    private javax.swing.JRadioButton RbRollos;
    private javax.swing.JRadioButton RbYarda;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable TableVentas;
    private javax.swing.JButton btnDespachar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDireccionClient;
    private javax.swing.JTextField txtNitClient;
    private javax.swing.JTextField txtNombreClient;
    // End of variables declaration//GEN-END:variables
}
