/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modificar;

import Clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carlo
 */
public class Mtela extends javax.swing.JPanel {
    Conexion con = new Conexion();
    Connection cn= con.ConectarBaseDatos();
    public int id_producto;
    

    /**
     * Creates new form Mtela
     */
    public Mtela(int id) {
        
        initComponents();
        mostrar_datos(id);
        id_producto=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboyarda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 41, 46));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtipo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        add(txtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 160, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Precio Venta");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        comboyarda.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        comboyarda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar", "50", "100", "200" }));
        comboyarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboyardaActionPerformed(evt);
            }
        });
        add(comboyarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 100, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Yardaje");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtcantidad.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, -1));

        txtcolor.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        add(txtcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 160, -1));

        txtPrecioVenta.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 160, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cambios.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cambios2.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cambios1.png"))); // NOI18N
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-------");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void comboyardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboyardaActionPerformed
        // TODO add your handling code here:
        switch(comboyarda.getSelectedIndex()){
            
            case 0:
                
                break;
            case 1:
                jLabel6.setText(String.valueOf(comboyarda.getSelectedItem()));
                break;
            case 2:
                jLabel6.setText(String.valueOf(comboyarda.getSelectedItem()));
                break;
            case 3:
                jLabel6.setText(String.valueOf(comboyarda.getSelectedItem()));
                break;
                
        }
                
        
    }//GEN-LAST:event_comboyardaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        modificar_datos();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void mostrar_datos(int id_productos){
        
        String sql="SELECT tipo,cantidad,yardaje,color,precio_venta FROM producto WHERE id_producto='"+id_productos+"'";
        Statement st;
        try {
            st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            
         while (rs.next()) {
            txtipo.setText(rs.getString(1));
            txtcantidad.setText(rs.getString(2));
            jLabel6.setText(rs.getString(3));
            txtcolor.setText(rs.getString(4));
            txtPrecioVenta.setText(rs.getString(5));
            
         }
        } catch (SQLException ex) {
            Logger.getLogger(Mtela.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    public void modificar_datos(){
        String tipo,color;
        int cantidad,yardaje;
        float precio;
        tipo=txtipo.getText();
        color=txtcolor.getText();
        cantidad=Integer.valueOf(txtcantidad.getText());
        yardaje=Integer.valueOf(jLabel6.getText());
        precio=Float.valueOf(txtPrecioVenta.getText());
        String sql="UPDATE producto SET tipo='"+tipo+"',cantidad='"+cantidad+"', yardaje='"+yardaje+"', color='"+color+"', precio_venta='"+precio+"' WHERE id_producto='"+id_producto+"'";
        PreparedStatement preparado;
        try {
            preparado = cn.prepareStatement(sql);
            preparado.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Mtela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboyarda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtipo;
    // End of variables declaration//GEN-END:variables
}
